spring.application.name=checkers-backend

launcher.api.url=http://localhost:8080

logging.level.sql=DEBUG
logging.level.web=DEBUG

spring.jpa.hibernate.ddl-auto=none
spring.docker.compose.enabled=false

ai.service.url=http://localhost:3334/ai-player/move

checkers.exchange.name=checkers-exchange
checkers.queue.name=checkers-queue
achievement.exchange.name=achievement-exchange