spring.jpa.hibernate.ddl-auto=create-drop

server.port=8087
spring.config.import=classpath:secret.properties
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#spring.sql.init.data-locations=classpath:sql/game-service-data.sql

spring.datasource.url=jdbc:postgresql://localhost:5445/checkersDb
spring.datasource.username=user
spring.datasource.password=password

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password