spring.application.name=checkers-backend

launcher.api.url=http://localhost:8080

logging.level.sql=DEBUG
logging.level.web=DEBUG

spring.jpa.hibernate.ddl-auto=none
spring.docker.compose.enabled=false

ai.service.url=http://xxx/ai-player/move
