spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
ai.service.url=http://localhost:8080
ai.service.api-key=test-key
game.title=Checkers from publish
game.description=Play with checkers
game.imageUrl=https://www.247checkers.com/images/how-to-play/Checkers-start1.png
game.gameUrl=http://localhost:5174/checkers/
game.price=20
game.genre=STRATEGY
game.maxlobbysize=2